#!/bin/sh
# configure ACQ480 with internal clock.
# for fpclk, call acq2106+acq42x.init fpclk SR FIN AFTER this program.

source /etc/profile.d/epics.sh

cp /usr/local/CARE/acq480_streamd.0.conf /etc/sysconfig/acq400_streamd.0.conf

PNAME=$(basename $0)

compat=$(cat /proc/device-tree/chosen/compatible_model)
case $compat in
z7io)
	;;
*)
	logger -t $PNAME "ERROR : script valid for Z7IO host ONLY"
	exit 1;;
esac

# CLK 40MHz too fast with 16ch, so decimate /2
set.site 1 ACQ480:FIR:01 LP_ODD_D2
FREQ=20
FREQHZ=$(($FREQ*1000000))


eval $(get.site 0 aggregator)
if [ "x$sites" = "xnone" ]; then
	logger -t $PNAME "WARNING: no sites in aggregator set"
	exit 1
fi

set.site 0 acq480_force_training 1
caput ${IOC_HOST}:1:INTCLK_HZ $FREQHZ

deltaF() {
	echo $(get.site 0 SIG:CLK_MB:FREQ) $FREQHZ 100000 | \
		awk '{ x=($2/$4 - $3/$4); printf("%d\n", (x>=0? x: -x)) }'
}

sleep 1
if [ $(deltaF) -ne 0 ]; then
	logger -t $PNAME "acq480_init_clk warning clock error"
fi

#set.site 0 SIG:CLK_MB:READY 1

